# Generated by Django 5.0.2 on 2024-03-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snc_python_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urlImage',
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        ),
    ]
