# Generated by Django 5.0.2 on 2024-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snc_python_api', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='urlImage',
            field=models.CharField(max_length=500),
        ),
    ]
