# Generated by Django 5.0.2 on 2024-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snc_python_api', '0005_alter_product_urlimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default="для всех типов волос", max_length=2000),
            preserve_default=False,
        ),
    ]
