# Generated by Django 5.0.2 on 2024-03-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snc_python_api', '0011_alter_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='typeProblem',
        ),
    ]
