# Generated by Django 5.0.2 on 2024-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snc_python_api', '0014_alter_product_typeproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=10)),
                ('dandruff', models.CharField(max_length=10)),
                ('dyed', models.CharField(max_length=10)),
                ('fallOut', models.CharField(max_length=10)),
            ],
        ),
    ]
